const KEY="srisai_vani_items_v2", SETTINGS="srisai_vani_settings_v2";
let sarees=JSON.parse(localStorage.getItem(KEY)||"null")||[
{id:1,name:"Banarasi Silk Saree",price:"4999",category:"Silk",color:"Ruby & Gold",description:"Lustrous silk with classic zari detailing.",image:"https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85",featured:true},
{id:2,name:"Kanchipuram Heritage",price:"6999",category:"Silk",color:"Blush Pink",description:"A festive silk drape with traditional character.",image:"https://images.unsplash.com/photo-1610189012906-1b89d7b2f4f5?auto=format&fit=crop&w=900&q=85",featured:true},
{id:3,name:"Handloom Cotton",price:"1799",category:"Cotton",color:"Indigo Blue",description:"Easy, breathable and beautifully textured.",image:"https://images.unsplash.com/photo-1583391733981-8498406f7f0c?auto=format&fit=crop&w=900&q=85",featured:true},
{id:4,name:"Festive Tissue Saree",price:"3299",category:"Festive",color:"Rose Gold",description:"Light-catching festive texture for evenings.",image:"https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85",featured:true}
];
let settings=JSON.parse(localStorage.getItem(SETTINGS)||"null")||{shopName:"SRI SAI VANI",whatsapp:"919999999999",about:"Sri Sai Vani Saree Collections brings together elegant sarees for weddings, celebrations and everyday moments.",footer:"Beautiful sarees, personal service."};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(sarees));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function wa(s){return "https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hi, I'm interested in "+s.name+" - ₹"+s.price+". Is it available?")}
function card(s){return '<article class="product-card"><div class="product-image">'+(s.featured?'<span class="badge">New arrival</span>':'')+'<img src="'+esc(s.image)+'" alt="'+esc(s.name)+'" style="width:100%;height:100%;object-fit:cover;position:absolute;inset:0" onerror="this.style.display=\'none\'"></div><div class="product-body"><h3>'+esc(s.name)+'</h3><div class="subline">'+esc(s.category)+' · '+esc(s.color)+'</div><div class="price-row"><span class="price">₹'+Number(s.price).toLocaleString("en-IN")+'</span><a class="small-wa whatsapp-mini" target="_blank" href="'+wa(s)+'" aria-label="Enquire on WhatsApp" title="Enquire on WhatsApp"><span class="wa-logo">◔</span></a></div></div></article>'}
function render(){const q=(document.getElementById("search")?.value||"").toLowerCase(),cat=document.getElementById("category")?.value||"";const list=sarees.filter(s=>(!q||(s.name+" "+s.category+" "+s.color+" "+s.description).toLowerCase().includes(q))&&(!cat||s.category===cat));document.getElementById("catalogGrid").innerHTML=list.map(card).join("");const featured=sarees.filter(s=>s.featured).slice(0,4);document.getElementById("featuredGrid").innerHTML=featured.map(card).join("");document.getElementById("empty").classList.toggle("hidden",list.length>0);const cats=[...new Set(sarees.map(s=>s.category).filter(Boolean))];const current=cat;document.getElementById("category").innerHTML='<option value="">All categories</option>'+cats.map(c=>'<option value="'+esc(c)+'">'+esc(c)+"</option>").join("");document.getElementById("category").value=current;document.getElementById("shopName").textContent=settings.shopName;document.getElementById("footerName").textContent=settings.shopName;document.getElementById("aboutInfo").textContent=settings.about;document.getElementById("footerInfo").textContent=settings.footer;document.getElementById("mainWa").href="https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hi, I'd like to see your saree collection.");}
function focusSearch(){document.getElementById("search").focus();document.getElementById("catalog").scrollIntoView({behavior:"smooth"})}
function setCategory(c){document.getElementById("category").value=c;document.getElementById("catalog").scrollIntoView({behavior:"smooth"});render()}
function toggleMenu(){const n=document.getElementById("mainNav");n.style.display=n.style.display==="flex"?"none":"flex";n.style.flexDirection="column";n.style.position="absolute";n.style.top="73px";n.style.left="0";n.style.right="0";n.style.background="#fffdfb";n.style.padding="20px 24px";n.style.borderBottom="1px solid #eee"}
function showAdmin(){document.getElementById("adminModal").classList.remove("hidden")}
function hideAdmin(){document.getElementById("adminModal").classList.add("hidden")}
function login(){if(document.getElementById("adminPassword").value==="admin123"){document.getElementById("loginBox").classList.add("hidden");document.getElementById("adminBox").classList.remove("hidden");openSareeList()}else alert("Incorrect password")}
function openSareeList(){document.getElementById("adminContent").innerHTML='<div class="admin-list">'+sarees.map(s=>'<div class="admin-item"><img src="'+esc(s.image)+'"><div class="grow"><b>'+esc(s.name)+'</b><br>₹'+Number(s.price).toLocaleString("en-IN")+' · '+esc(s.category)+'</div><button onclick="openSareeForm('+s.id+')">Edit</button><button class="danger" onclick="deleteItem('+s.id+')">Delete</button></div>').join("")+"</div>"}
function openSareeForm(id=null){const s=id?sarees.find(x=>x.id===id):{name:"",price:"",category:"Silk",color:"",description:"",image:"",featured:false};document.getElementById("adminContent").innerHTML='<div class="form"><label>Name<input id="fName" value="'+esc(s.name)+'"></label><div class="row"><label>Price<input id="fPrice" type="number" value="'+esc(s.price)+'"></label><label>Category<input id="fCategory" value="'+esc(s.category)+'"></label></div><label>Colour<input id="fColor" value="'+esc(s.color)+'"></label><label>Description<textarea id="fDesc">'+esc(s.description)+'</textarea></label><label>Image URL<input id="fImage" value="'+esc(s.image)+'"></label><label>Upload image<input id="fFile" type="file" accept="image/*" onchange="previewFile(this)"></label><img id="fPreview" class="preview '+(s.image?'':'hidden')+'" src="'+esc(s.image)+'"><label><input id="fFeatured" type="checkbox" '+(s.featured?'checked':'')+'> Show as new arrival</label><div><button class="btn dark" onclick="saveItem('+(id||"null")+')">Save Item</button> <button class="btn" onclick="openSareeList()">Cancel</button></div></div>'}
function previewFile(input){if(input.files[0]){const r=new FileReader();r.onload=()=>{fImage.value=r.result;fPreview.src=r.result;fPreview.classList.remove("hidden")};r.readAsDataURL(input.files[0])}}
function saveItem(id){const d={name:fName.value.trim(),price:fPrice.value,category:fCategory.value.trim(),color:fColor.value.trim(),description:fDesc.value.trim(),image:fImage.value.trim(),featured:fFeatured.checked};if(!d.name||!d.price||!d.image)return alert("Name, price and image are required.");if(id)Object.assign(sarees.find(x=>x.id===id),d);else sarees.unshift({id:Date.now(),...d});save();render();openSareeList()}
function deleteItem(id){if(confirm("Delete this item?")){sarees=sarees.filter(s=>s.id!==id);save();render();openSareeList()}}
function openSettings(){document.getElementById("adminContent").innerHTML='<div class="form"><label>Shop name<input id="setName" value="'+esc(settings.shopName)+'"></label><label>WhatsApp number<input id="setWa" value="'+esc(settings.whatsapp)+'" placeholder="9198..."></label><label>Our story<textarea id="setAbout">'+esc(settings.about)+'</textarea></label><label>Footer line<input id="setFooter" value="'+esc(settings.footer)+'"></label><button class="btn dark" onclick="saveSettings()">Save settings</button></div>'}
function saveSettings(){settings={shopName:setName.value.trim()||"SRI SAI VANI",whatsapp:setWa.value.replace(/\D/g,""),about:setAbout.value.trim(),footer:setFooter.value.trim()};save();render();alert("Settings saved")}
render();